DEBUG_ONLY_TOKENS = False
DEBUG_SHOW_ERROR_TOKEN = False
DEBUG_SHOW_VARIABLES_AT_END = False
DEBUG_SHOW_RAW_ERROR = False
DEBUG_SHOW_TIME_TAKEN = False

if DEBUG_ONLY_TOKENS:
    print("\033[33mDEBUG_ONLY_TOKENS ACTIVE\033[0m")
if DEBUG_SHOW_ERROR_TOKEN:
    print("\033[33mDEBUG_SHOW_ERROR_TOKEN ACTIVE\033[0m")
if DEBUG_SHOW_VARIABLES_AT_END:
    print("\033[33mDEBUG_SHOW_VARIABLES_AT_END ACTIVE\033[0m")
if DEBUG_SHOW_RAW_ERROR:
    print("\033[33mDEBUG_SHOW_RAW_ERROR ACTIVE\033[0m")
if DEBUG_SHOW_TIME_TAKEN:
    print("\033[33mDEBUG_SHOW_TIME_TAKEN ACTIVE\033[0m")